name: travel


services:
  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    entrypoint: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      - db
      - redis


volumes:
  postgres_data:
  redis_data: